### PR TITLE
refactor(views/SignIn): split component and hooks

### LINKED ISSUE #82: Add Autocomplete and ARIA Attributes to Form Fields in SignIn View
## Description

Currently, the SignIn view does not fully adhere to accessibility and HTML standards. Specifically, the form fields in the SignIn view lack the necessary autocomplete and ARIA (Accessible Rich Internet Applications) attributes.

The Chrome browser console flags the following error:

```
[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input aria-invalid=​"false" id=​"auth-login-v2-password" type=​"password" class=​"MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd css-1u6bhim-MuiInputBase-input-MuiOutlinedInput-input" value>​
```

This error indicates that the password input field should have an autocomplete attribute, specifically `autocomplete="current-password"`.

Additionally, the email and password fields, as well as the "Login" and "Login with IDP" buttons, lack ARIA attributes that provide essential information to assistive technologies.

## Expected Behavior

All form fields in the SignIn view should have the appropriate autocomplete and ARIA attributes. This includes:

- The email field should have an `autocomplete="email"` attribute and the necessary ARIA attributes.
- The password field should have an `autocomplete="current-password"` attribute and the necessary ARIA attributes.
- The "Login" and "Login with IDP" buttons should have the necessary ARIA attributes.

## Possible Solution

Update the SignIn view to include these attributes. For instance, the password input field can be updated as follows:

```jsx
<input
  type="password"
  autocomplete="current-password"
  aria-labelledby="labelId"
  aria-required="true"
  id="auth-login-v2-password"
  class="MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd css-1u6bhim-MuiInputBase-input-MuiOutlinedInput-input"
/>
```

The other fields and buttons can be updated in a similar manner.

## Additional Context

Adhering to these standards will improve the accessibility of the application and provide a better user experience for all users, including those using assistive technologies. It also helps all browsers autofill forms for users, improving the overall user experience.

### PR DESCRIPTION
**Pull request by sbolel**
## Summary

This PR focuses on improving the accessibility and best practices of the existing sign-in view. It splits the SignIn view into multiple files, and pulls out hooks into a custom hook instead of implementing them inside the component itself. It also includes changes related to the file structure, moving all sign-in related files into a single directory.

The main changes are:
- The form input fields now have associated labels that are correctly linked using the "for" attribute for better accessibility.
- The usage of `react-hook-form` library for managing form state and validation is now consistent throughout the entire form.
- Error messages are now tied to the corresponding input field with `aria-describedby` attribute, improving accessibility.
- Created a new form component `FormControlInput` that is a reusable form input with react-hook-form controls.
- Created a new helper component `PasswordVisibilityToggle` to manage the show/hide password functionality, enhancing code reusability.
- Extracted custom styled components into a separate module to keep the main component code cleaner.
- The form's submit handler now checks the form validity before proceeding with the login logic.
- The sign-in hook now uses the Auth module from AWS Amplify for handling the federated sign in.
- Introduced Jest tests for the `useSignIn` hook, increasing the code's reliability.

Other:
- moved `SignInGraphic` into `SignIn.components.tsx`

## Related Issues

- Closes #82 

## How to test

- `yarn start` - start the application and log in to verify that the sign in page behaves as expected.

**Coverage:**

```
-------------------------------------|---------|----------|---------|---------|---------------------------
File                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------------------------|---------|----------|---------|---------|---------------------------
 src/components                      |         |          |         |         |
  PasswordVisibilityToggle.tsx       |     100 |      100 |     100 |     100 |
 src/components/forms                |     100 |    81.81 |     100 |     100 |
  InputFormControl.tsx               |     100 |       80 |     100 |     100 | 31-52
  SubmitButton.tsx                   |     100 |      100 |     100 |     100 |
 src/views/SignIn                    |    97.5 |      100 |    92.3 |    98.5 |
  SignIn.components.tsx              |      92 |      100 |    87.5 |   92.85 | 61
  SignIn.tsx                         |     100 |    57.14 |     100 |     100 | 133,149
  useSignIn.ts                       |   75.75 |      100 |   66.66 |      75 | 82-92
```

### CODE REVIEW

**Review by qtpeters — CHANGES_REQUESTED** [review]
I'm having a hard time correctly configuring this application.  I have a file named: `.env.development.local`  I have been using to configure it, however I'm still getting:

image

because `UserPoolId` is not undefined.  I tried having that config file at the root of the application, then I put exports on the variables in the file and imported the variables into the environment. Neither worked.  Do me a monster favor and put detailed configuration instructions into the README or the PR instructions (README is better because it will stay there for future reference) and I'll review it again.

**Comment by sbolel** [comment]
@qtpeters all you need to do is

```sh
cp .env.test .env.development.local
```

and then enter in the right values for the dev environment. I sent you these values on Slack.

**Review by DerekStrickland — DISMISSED** [review]
All tests passing

**Review by qtpeters — APPROVED** [review]
Testing it worked.  LGTM

**Review by qtpeters — APPROVED** [review]
:+1:

**Pull request merged**
