### PR TITLE
build: ignore coverage files for HMR

### PR DESCRIPTION
**Pull request by sbolel**
## Summary

This PR updates the Vite server configuration to ignore file changes in the coverage directory, which helps optimize the hot module reload (HMR) process.

### Added

- Added an 'ignored' property to the Vite server watch configuration. This property specifies an array of glob patterns, with `'**/coverage/**'` currently defined to ignore all files in any coverage directory. 

### Changed

- No existing functionality has been modified outside of the added configuration.

### Deprecated

- No features or components have been marked for deprecation.

### Removed

- No features or components have been removed.

### Fixed

- This configuration update indirectly addresses any potential performance or unnecessary HMR triggers caused by changes in coverage files during development.

## How to test

- After pulling the changes, start the local development server with `yarn start`
- While the server is running, make changes to files within a coverage directory or run `yarn test` and observe that HMR does not get triggered. 
- Verify that changes to other files (not in the coverage directory) still trigger HMR as expected.

### CODE REVIEW

**Comment by qtpeters** [comment]
> After pulling the changes, run the Vite server in development mode.

Please be specific.  How do I run Vite in development mode?  I looked at the documentation and it says I run:
`vite --mode <???>`

**Review by qtpeters — DISMISSED** [review]
Update testing instructions to be specific.

**Comment by sbolel** [comment]
> Please be specific. How do I run Vite in development mode? I looked at the documentation and it says I run:

@qtpeters, you need to run `yarn start` to start the local development server. Updated testing instructions.

**Review by qtpeters — APPROVED** [review]
Works as expected

**Pull request merged**
